import Head from 'next/head'
import Image from 'next/image'

import "@material-tailwind/react/tailwind.css";
import Icon from "@material-tailwind/react/Icon";




export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Alkimera Soluções Digitais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoalk.ico" />
      </Head>

      <main className="h-screen">
        <div className="h-20"></div>

        <div className="space-y-2 p-4 sm:flex">
        {/* bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 */}
          <span class="font-extrabold text-8xl bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-pink-500 to-red-500">
            Alkimera Soluções Digitais
          </span>

          <h3 className="pb-4 text-white text-xl font-extralight">
            Projetos sob demanda.
          </h3>
        </div>


        <div className="flex fixed bottom-14 right-0">
          <a class="right-0 animate-pulse" href="https://bit.ly/Site-wpp" target="_blank">
            <img src="/wpp.png" width="100" />
          </a>
        </div>
      </main>

      <footer className="text-white text-center justify-center font-extralight">
        <p>Copyright &copy; <span>2021</span> Desenvolvido por <span className="font-semibold text-green-400 cursor-pointer">Alkimera</span> 👾</p>
      </footer>
    </div>
  )
}
